# Generated by Django 5.2.16 on 2026-08-19 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('longueur', models.PositiveIntegerField(blank=True, null=True)),
                ('largeur', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('decoupe', models.BooleanField(default=True)),
                ('rabotage', models.BooleanField(default=False)),
                ('percage', models.BooleanField(default=False)),
                ('trempe', models.BooleanField(default=False)),
                ('autres_prestations', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=24, unique=True)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('VALIDEE', 'Validée'), ('EN_PREPARATION', 'En préparation'), ('EN_PRODUCTION', 'En production'), ('TERMINEE', 'Terminée'), ('PRETE', 'Prête'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='clients.client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'permissions': [('validate_commande', 'Peut valider une commande'), ('manage_commande', 'Peut gérer les commandes')],
            },
        ),
    ]
