# Generated by Django 5.2.16 on 2026-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epaisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='mm', max_digits=5, unique=True)),
            ],
            options={
                'ordering': ['valeur'],
            },
        ),
        migrations.CreateModel(
            name='Finition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['designation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['designation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeVerre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['designation'],
                'abstract': False,
            },
        ),
    ]
