# Generated by Django 5.2.16 on 2026-07-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chutes', '0002_remove_chute_finition'),
        ('panneaux', '0002_remove_panneau_finition'),
        ('types_verres', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finition',
        ),
    ]
