# Generated by Django 5.2.16 on 2026-08-19 15:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types_verres', '0002_delete_finition'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeverre',
            name='prix_m2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarif de référence en francs CFA pour un mètre carré.', max_digits=12, verbose_name='Prix au m² (FCFA)'),
        ),
    ]
