# Generated by Django 5.2.16 on 2026-08-19 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=24, unique=True)),
                ('statut', models.CharField(choices=[('A_PREPARER', 'À préparer'), ('EN_COURS', 'En cours'), ('BLOQUEE', 'Bloquée'), ('TERMINEE', 'Terminée')], default='A_PREPARER', max_length=16)),
                ('priorite', models.CharField(default='NORMALE', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_production', to='commandes.commande')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_production', 'Peut gérer la production'), ('operate_production', 'Peut opérer les étapes de production'), ('control_quality', 'Peut effectuer le contrôle qualité')],
            },
        ),
        migrations.CreateModel(
            name='PieceProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(default='A_FAIRE', max_length=16)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='production.ficheproduction')),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commandes.lignecommande')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DECOUPE', 'Découpe'), ('RABOTAGE', 'Rabotage'), ('PERCAGE', 'Perçage'), ('TREMPE', 'Trempe'), ('CONTROLE', 'Contrôle qualité')], max_length=12)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminée'), ('BLOQUE', 'Bloquée'), ('NON_CONFORME', 'Non conforme')], default='A_FAIRE', max_length=16)),
                ('debut', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('probleme', models.TextField(blank=True)),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='production.pieceproduction')),
            ],
            options={
                'unique_together': {('piece', 'type')},
            },
        ),
    ]
