# Generated by Django 5.2.16 on 2026-07-31 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('types_verres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('longueur', models.PositiveIntegerField(help_text='mm')),
                ('largeur', models.PositiveIntegerField(help_text='mm')),
                ('surface', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12)),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EPUISE', 'Épuisé'), ('ARCHIVE', 'Archivé')], default='DISPONIBLE', max_length=12)),
                ('epaisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.epaisseur')),
                ('finition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.finition')),
                ('teinte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.teinte')),
                ('type_verre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.typeverre')),
            ],
            options={
                'ordering': ['-date_entree'],
            },
        ),
    ]
