# Generated by Django 5.2.16 on 2026-07-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panneaux', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panneau',
            name='finition',
        ),
    ]
