# Generated by Django 5.2.16 on 2026-07-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panneaux', '0002_remove_panneau_finition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panneau',
            name='prix',
        ),
    ]
