# Generated by Django 5.2.16 on 2026-08-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoupes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoupe',
            options={'ordering': ['-cree_le'], 'permissions': [('plan_cut', 'Peut planifier et valider une découpe')]},
        ),
    ]
