# Generated by Django 5.2.16 on 2026-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('chariot', models.CharField(max_length=50)),
                ('niveau', models.PositiveSmallIntegerField()),
                ('case', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['chariot', 'niveau', 'case'],
                'constraints': [models.UniqueConstraint(fields=('chariot', 'niveau', 'case'), name='emplacement_unique')],
            },
        ),
    ]
