# Generated by Django 5.2.16 on 2026-07-31 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emplacements', '0001_initial'),
        ('types_verres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=32, unique=True)),
                ('longueur', models.PositiveIntegerField()),
                ('largeur', models.PositiveIntegerField()),
                ('surface', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('origine', models.CharField(blank=True, max_length=120)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('UTILISEE', 'Utilisée'), ('DECHET', 'Déchet')], default='DISPONIBLE', max_length=12)),
                ('code_qr', models.CharField(blank=True, max_length=128, unique=True)),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emplacements.emplacement')),
                ('epaisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.epaisseur')),
                ('finition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.finition')),
                ('teinte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.teinte')),
                ('type_verre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='types_verres.typeverre')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
