# Generated by Django 5.2.16 on 2026-08-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_offcuts(apps, schema_editor):
    Chute = apps.get_model('chutes', 'Chute')
    MouvementChute = apps.get_model('chutes', 'MouvementChute')
    Chute.objects.filter(etat='DECHET').update(etat='REBUT')
    for chute in Chute.objects.all().iterator():
        if not MouvementChute.objects.filter(chute_id=chute.pk).exists():
            MouvementChute.objects.create(
                chute_id=chute.pk, action='CREATION', nouveau_statut=chute.etat,
                nouvel_emplacement_id=chute.emplacement_id,
                nouvelles_dimensions=f'{chute.longueur} × {chute.largeur} mm',
                commentaire='Historique initialisé lors de la migration de traçabilité.',
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chutes', '0002_remove_chute_finition'),
        ('emplacements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chute',
            options={'ordering': ['-date_creation'], 'permissions': [('move_chute', 'Peut déplacer une chute'), ('correct_chute', 'Peut corriger une chute'), ('reserve_chute', 'Peut réserver une chute'), ('use_chute', 'Peut utiliser une chute'), ('discard_chute', 'Peut mettre une chute au rebut'), ('view_chute_history', "Peut consulter l'historique des chutes")]},
        ),
        migrations.AddField(
            model_name='chute',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chute',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chutes_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chute',
            name='reservation_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='chute',
            name='etat',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVEE', 'Réservée'), ('UTILISEE', 'Utilisée'), ('REBUT', 'Rebut')], default='DISPONIBLE', max_length=12),
        ),
        migrations.CreateModel(
            name='MouvementChute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('DEPLACEMENT', 'Déplacement'), ('CORRECTION', 'Correction'), ('RESERVATION', 'Réservation'), ('ANNULATION_RESERVATION', 'Annulation réservation'), ('UTILISATION', 'Utilisation'), ('REBUT', 'Mise au rebut')], max_length=24)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=12)),
                ('nouveau_statut', models.CharField(blank=True, max_length=12)),
                ('anciennes_dimensions', models.CharField(blank=True, max_length=40)),
                ('nouvelles_dimensions', models.CharField(blank=True, max_length=40)),
                ('motif', models.CharField(blank=True, choices=[('CASSE', 'Cassé'), ('RAYURE', 'Rayure'), ('DEFAUT', 'Défaut'), ('DIMENSION_INCORRECTE', 'Dimension incorrecte'), ('DETERIORATION', 'Détérioration'), ('AUTRE', 'Autre')], max_length=32)),
                ('commentaire', models.TextField(blank=True)),
                ('ancien_emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_chutes_depart', to='emplacements.emplacement')),
                ('chute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique', to='chutes.chute')),
                ('nouvel_emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_chutes_arrivee', to='emplacements.emplacement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'permissions': [],
            },
        ),
        migrations.RunPython(migrate_legacy_offcuts, noop),
    ]
