# Generated by Django 5.2.16 on 2026-08-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panneaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockgrandpanneau',
            options={'ordering': ['reference'], 'permissions': [('manage_stock', 'Peut gérer le stock de panneaux')], 'verbose_name': 'stock de grand panneau', 'verbose_name_plural': 'stocks de grands panneaux'},
        ),
    ]
