# Generated by Django 5.2.16 on 2026-08-19 11:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('types_verres', '0002_delete_finition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('produits', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ETUDE', 'En étude'), ('DEVIS_EN_PREPARATION', 'Devis en préparation'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('TERMINE', 'Terminée')], default='BROUILLON', max_length=24)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_devis', to='clients.client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=24, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=16)),
                ('date', models.DateField(auto_now_add=True)),
                ('validite', models.DateField(blank=True, null=True)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('observations', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='clients.client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='commercial.demandedevis')),
            ],
            options={
                'ordering': ['-date', '-pk'],
                'permissions': [('send_devis', 'Peut envoyer un devis'), ('accept_devis', 'Peut accepter un devis'), ('transform_devis', 'Peut transformer un devis en commande')],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('longueur', models.PositiveIntegerField(blank=True, null=True)),
                ('largeur', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decoupe', models.BooleanField(default=True)),
                ('rabotage', models.BooleanField(default=False)),
                ('percage', models.BooleanField(default=False)),
                ('trempe', models.BooleanField(default=False)),
                ('autres_prestations', models.CharField(blank=True, max_length=240)),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commercial.devis')),
                ('epaisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='types_verres.epaisseur')),
                ('type_verre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='types_verres.typeverre')),
            ],
        ),
    ]
