# Generated by Django 5.2.16 on 2026-08-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('types_verres', '0002_delete_finition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date', '-pk'], 'permissions': [('send_devis', 'Peut envoyer un devis'), ('accept_devis', 'Peut accepter un devis'), ('refuse_devis', 'Peut refuser un devis'), ('cancel_devis', 'Peut annuler un devis'), ('transform_devis', 'Peut transformer un devis en commande')]},
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Ex. 1200 × 800 mm', max_length=120),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='epaisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='types_verres.epaisseur'),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='prestations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='type_verre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='types_verres.typeverre'),
        ),
        migrations.CreateModel(
            name='HistoriqueDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=16)),
                ('nouveau_statut', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique', to='commercial.devis')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
    ]
