# Generated by Django 5.2.16 on 2026-08-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_alter_devis_options_demandedevis_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Prix au m² (FCFA)'),
        ),
    ]
