# Generated by Django 5.2.16 on 2026-09-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chutes', '0003_alter_chute_options_chute_modifie_le_and_more'),
        ('commercial', '0003_alter_lignedevis_prix_unitaire'),
        ('stock_panneaux', '0002_alter_stockgrandpanneau_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='stock_mis_a_jour_le',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='chute_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='chutes.chute'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='panneau_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='stock_panneaux.stockgrandpanneau'),
        ),
    ]
