# Generated by Django 5.2.16 on 2026-09-03 13:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_devis_stock_mis_a_jour_le_lignedevis_chute_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='acompte_taux',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_adresse',
            field=models.TextField(blank=True, help_text='Adresse de pose ou de livraison si différente du client'),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_telephone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='devis',
            name='conditions_paiement',
            field=models.TextField(blank=True, default='50 % à la commande, solde à la livraison.'),
        ),
        migrations.AddField(
            model_name='devis',
            name='delai_fabrication',
            field=models.CharField(blank=True, help_text='Ex. 7 à 10 jours ouvrés après validation', max_length=120),
        ),
        migrations.AddField(
            model_name='devis',
            name='pose_incluse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devis',
            name='prise_mesures_validee',
            field=models.BooleanField(default=False, help_text='Dimensions relevées et validées sur site'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='prix_prestations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Forfait prestations HT (FCFA)'),
        ),
    ]
