# Generated by Django 5.2.16 on 2026-09-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_devis_acompte_taux_devis_chantier_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='stock_mis_a_jour_le',
        ),
    ]
