# Generated by Django 5.2.16 on 2026-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_remove_devis_stock_mis_a_jour_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedevis',
            name='chantier_adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='contact_chantier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='date_souhaitee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='pose_souhaitee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='priorite',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='prise_mesures_souhaitee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='telephone_chantier',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='titre',
            field=models.CharField(blank=True, help_text='Ex. Vitrine boutique, remplacement de baie, garde-corps', max_length=160),
        ),
    ]
